"""Constants for Face Recognizer."""

DAEMON_NAME = "face-recognizer"
DEFAULT_DETECTOR = "insightface"
DEFAULT_DETECTION_VIEW_MAX_SIZE = 4000
FACES_DIR = "faces"
DEFAULT_FACE_THUMB_MAX_SIZE = 256
DEFAULT_FACE_THUMB_PADDING = 0.15
